package io.github.ygrip.testara.agent.skill.run;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Builds safe Gradle commands for Cucumber test execution without touching the project's build
 * scripts.
 *
 * <p>Cucumber options travel as {@code -Pcucumber.*} project properties; an agent-owned init script
 * ({@value #INIT_SCRIPT_PATH}) copies them onto every {@code Test} task as JVM system properties, so
 * they reach both the JUnit 4 runner and the JUnit Platform engine (which does not read environment
 * variables). The init script also disables up-to-date checks and the build cache for {@code Test}
 * tasks so a repeated agent run always executes and writes a fresh report.
 */
public class GradleCommandBuilder {

  public static final String DEFAULT_TASK = "test";
  public static final String INIT_SCRIPT_PATH = ".testara-agent/gradle/testara-cucumber.init.gradle";

  static final String INIT_SCRIPT = """
      // Generated by testara-agent; safe to delete. Used only via --init-script on agent test runs.
      // Forwards -Pcucumber.* project properties to every Test task as JVM system properties.
      def cucumberProperties = gradle.startParameter.projectProperties.findAll { key, value ->
        key.startsWith('cucumber.')
      }
      allprojects {
        tasks.withType(Test).configureEach {
          systemProperties(cucumberProperties)
          outputs.upToDateWhen { false }
          outputs.cacheIf { false }
        }
      }
      """;

  private static final Pattern SAFE_TASK = Pattern.compile("^[A-Za-z][\\w-]*$");

  /** Tag-filtered run: {@code <gradle> [:module:]task --console=plain --init-script <script> -Pcucumber.filter.tags=<expr>}. */
  public BuildCommand build(Path projectRoot, String tagExpression, String module, String task) {
    RunArguments.requireValidTagExpression(tagExpression);
    return command(projectRoot, module, task, "-Pcucumber.filter.tags=" + tagExpression,
        "-Pcucumber.filter.tags=\"" + tagExpression + "\"");
  }

  /** Rerun-file run using Cucumber's native {@code @<rerun-file>} feature path. */
  public BuildCommand buildRerun(Path projectRoot, Path rerunFile, String module, String task) {
    String property = "-Pcucumber.features=@" + rerunFile;
    return command(projectRoot, module, task, property, property);
  }

  /** Absolute location of the agent-owned init script for {@code projectRoot}. */
  public static Path initScriptPath(Path projectRoot) {
    return projectRoot.toAbsolutePath().resolve(INIT_SCRIPT_PATH).normalize();
  }

  /** (Re)write the init script; call before executing a command built by this class. */
  public Path writeInitScript(Path projectRoot) throws IOException {
    Path script = initScriptPath(projectRoot);
    Files.createDirectories(script.getParent());
    Files.writeString(script, INIT_SCRIPT, StandardCharsets.UTF_8);
    return script;
  }

  static String taskPath(String module, String task) {
    String effectiveTask = DEFAULT_TASK;
    if (task != null && !task.isBlank()) {
      effectiveTask = task.strip();
    }
    if (!SAFE_TASK.matcher(effectiveTask).matches()) {
      throw new IllegalArgumentException("Gradle task must be a plain task name (e.g. test), got: " + task);
    }
    String projectPath = RunArguments.gradleProjectPath(module);
    if (projectPath == null) {
      return effectiveTask;
    }
    return projectPath + ":" + effectiveTask;
  }

  private BuildCommand command(Path projectRoot, String module, String task, String property,
      String displayProperty) {
    String taskPath = taskPath(module, task);
    String initScript = initScriptPath(projectRoot).toString();
    String launcher = ProcessRunner.gradleLauncher(projectRoot);
    // --no-daemon: the tests run in this build's process tree, so a timeout kill stops them too
    List<String> argv = List.of(launcher, taskPath, "--console=plain", "--no-daemon", "--init-script", initScript,
        property);
    String display = Path.of(launcher).getFileName() + " " + taskPath + " --console=plain --no-daemon --init-script "
        + initScript + " " + displayProperty;
    return new BuildCommand(argv, display);
  }
}
