package io.github.ygrip.testara.agent.skill;

import java.util.List;
import java.util.Locale;

/**
 * Skill: bootstrap a new Testara automation project or integrate Testara into an existing one.
 * Returns a patch plan (files to create/update) without writing anything unless APPLY mode is used.
 */
public class TestInitSkill implements AgentSkill<TestInitSkill.Input, String> {

  public record Input(String type, String basePackage, String engine, boolean integrateExisting) {}

  @Override
  public String name() { return "test-init"; }

  @Override
  public String execute(Input input, AgentContext context) {
    String type       = input.type() != null ? input.type() : "api";
    String basePkg    = input.basePackage() != null ? input.basePackage() : "com.company.automation";
    String pkgPath    = basePkg.replace('.', '/');
    boolean integrate = input.integrateExisting();

    StringBuilder sb = new StringBuilder();
    sb.append("# Testara Init: ").append(type.toUpperCase(Locale.ROOT)).append(" Project\n\n");
    sb.append(integrate
        ? "> **Integration mode** — only missing files will be added.\n\n"
        : "> **Bootstrap mode** — full project scaffold.\n\n");

    sb.append("## Files to Create\n\n");
    getFilesToCreate(type, basePkg, pkgPath, input.engine()).forEach(f ->
        sb.append("- `").append(f).append("`\n"));
    sb.append("\n");

    sb.append("## pom.xml Dependencies\n\n```xml\n");
    sb.append(generatePomDependencies(type, input.engine()));
    sb.append("```\n\n");

    sb.append("## configuration.properties\n\n```properties\n");
    sb.append(generateProperties(type, basePkg));
    sb.append("```\n\n");

    if ("ui".equalsIgnoreCase(type) || "fullstack".equalsIgnoreCase(type)) {
      sb.append("## Page Object Skeleton\n\n```java\n");
      sb.append(generatePageObject(basePkg, input.engine()));
      sb.append("```\n\n");
    }

    sb.append("## Runner Class\n\n```java\n");
    sb.append(generateRunner(basePkg));
    sb.append("```\n");
    return sb.toString();
  }

  private List<String> getFilesToCreate(String type, String basePkg, String pkgPath, String engine) {
    List<String> common = List.of(
        "pom.xml",
        "src/test/resources/configuration.properties",
        "src/test/resources/features/.gitkeep",
        "src/test/resources/files/.gitkeep",
        "src/test/resources/validations/.gitkeep",
        "src/test/java/" + pkgPath + "/runner/TestRunner.java",
        "src/test/java/" + pkgPath + "/steps/StepDefinitions.java");
    if ("ui".equalsIgnoreCase(type) || "fullstack".equalsIgnoreCase(type)) {
      return listOf(common, List.of(
          "src/test/java/" + pkgPath + "/pages/BasePage.java",
          "src/test/java/" + pkgPath + "/actions/BaseAction.java"));
    }
    return common;
  }

  private String generatePomDependencies(String type, String engine) {
    StringBuilder sb = new StringBuilder();
    sb.append("""
        <!-- Testara core -->
        <dependency>
          <groupId>io.github.ygrip</groupId>
          <artifactId>testara-api-cucumber</artifactId>
          <version>2.0.0</version>
          <scope>test</scope>
        </dependency>
        """);
    if ("ui".equalsIgnoreCase(type) || "fullstack".equalsIgnoreCase(type)) {
      String uiModule = resolveUiModule(engine);
      sb.append("""
          <dependency>
            <groupId>io.github.ygrip</groupId>
            <artifactId>%s</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
          </dependency>
          """.formatted(uiModule));
    }
    return sb.toString();
  }

  private String generateProperties(String type, String basePkg) {
    return """
        # Testara configuration
        cucumber.glue=%s.steps,io.github.ygrip.testara
        cucumber.features=src/test/resources/features
        cucumber.plugin=json:target/cucumber.json, html:target/cucumber-reports

        # Environment
        base.url=http://localhost:8080
        """.formatted(basePkg);
  }

  private String generateRunner(String basePkg) {
    return """
        package %s.runner;

        import io.cucumber.junit.platform.engine.Constants;
        import org.junit.platform.suite.api.*;

        @Suite
        @IncludeEngines("cucumber")
        @ConfigurationParameter(key = Constants.GLUE_PROPERTY_NAME,
            value = "%s.steps,io.github.ygrip.testara")
        @ConfigurationParameter(key = Constants.FEATURES_PROPERTY_NAME,
            value = "src/test/resources/features")
        @ConfigurationParameter(key = Constants.PLUGIN_PROPERTY_NAME,
            value = "json:target/cucumber.json")
        public class TestRunner {}
        """.formatted(basePkg, basePkg);
  }

  private String generatePageObject(String basePkg, String engine) {
    return """
        package %s.pages;

        import io.github.ygrip.testara.ui.page.PageContext;

        /**
         * Generated by Testara Agent — review before committing.
         */
        public class BasePage {

          protected final PageContext page;

          public BasePage(PageContext page) {
            this.page = page;
          }
        }
        """.formatted(basePkg);
  }

  private String resolveUiModule(String engine) {
    if ("playwright".equalsIgnoreCase(engine)) return "testara-ui-cucumber";
    if ("appium".equalsIgnoreCase(engine))     return "testara-ui-cucumber";
    return "testara-ui-cucumber";
  }

  @SafeVarargs
  private static <T> List<T> listOf(List<T>... lists) {
    List<T> result = new java.util.ArrayList<>();
    for (List<T> l : lists) result.addAll(l);
    return result;
  }
}
