package io.github.ygrip.testara.agent.skill;

import java.util.Locale;

/**
 * Skill: generate a Testara CommandLogic<T> class + unit test from a natural-language description.
 */
public class TestCommandSkill implements AgentSkill<String, String> {

  @Override
  public String name() { return "test-command"; }

  @Override
  public String execute(String description, AgentContext context) {
    String commandName = toCommandName(description);
    String className   = toClassName(commandName) + "Command";
    String basePackage = context.options().getOrDefault("package", "com.company.automation.commands");
    String returnType  = context.options().getOrDefault("returnType", "String");

    StringBuilder sb = new StringBuilder();
    sb.append("## Generated Command: `").append(commandName).append("`\n\n");
    sb.append("### ").append(className).append(".java\n\n```java\n");
    sb.append(generateCommandClass(className, commandName, description, basePackage, returnType));
    sb.append("```\n\n");
    sb.append("### ").append(className).append("Test.java\n\n```java\n");
    sb.append(generateCommandTest(className, commandName, basePackage, returnType));
    sb.append("```\n\n");
    sb.append("### Placement\n\n");
    sb.append("```\nsrc/test/java/").append(basePackage.replace('.', '/')).append("/")
        .append(className).append(".java\n```\n\n");
    sb.append("### Scan Location Config\n\n");
    sb.append("```properties\ncommand.executor.scan-locations=io.github.ygrip.testara,")
        .append(basePackage).append("\n```\n");
    return sb.toString();
  }

  private String generateCommandClass(String className, String commandName, String description,
      String pkg, String returnType) {
    return """
        package %s;

        import io.github.ygrip.testara.command.model.CommandLogic;
        import io.github.ygrip.testara.command.model.CommandTag;

        import java.util.List;

        /**
         * %s
         * Generated by Testara Agent — review before committing.
         */
        @CommandTag(command = "%s")
        public class %s implements CommandLogic<%s> {

          @Override
          public boolean preProcessParameters() {
            return false;
          }

          @Override
          public %s execute(List<Object> parameters) throws Exception {
            // TODO: implement command logic
            // parameters.get(0) = first argument passed in the command expression
            throw new UnsupportedOperationException("Not yet implemented");
          }
        }
        """.formatted(pkg, description, commandName, className, returnType, returnType);
  }

  private String generateCommandTest(String className, String commandName, String pkg, String returnType) {
    return """
        package %s;

        import org.junit.jupiter.api.Test;
        import java.util.List;
        import static org.junit.jupiter.api.Assertions.*;

        class %sTest {

          private final %s command = new %s();

          @Test
          void preProcessParameters_returnsFalse() {
            assertFalse(command.preProcessParameters());
          }

          @Test
          void execute_withEmptyParams_throwsOrReturnsResult() {
            // TODO: replace with actual assertion once implemented
            assertThrows(UnsupportedOperationException.class,
                () -> command.execute(List.of()));
          }
        }
        """.formatted(pkg, className, className, className);
  }

  private String toCommandName(String description) {
    return description.toLowerCase(Locale.ROOT)
        .replaceAll("[^a-z0-9]+", "-")
        .replaceAll("^-|-$", "")
        .substring(0, Math.min(40, description.length()));
  }

  private String toClassName(String commandName) {
    String[] parts = commandName.split("[-_]");
    StringBuilder sb = new StringBuilder();
    for (String p : parts) {
      if (!p.isBlank()) sb.append(Character.toUpperCase(p.charAt(0))).append(p.substring(1));
    }
    return sb.toString();
  }
}
