package io.github.ygrip.testara.agent.skill;

import io.github.ygrip.testara.agent.index.StepDefinitionIndex;
import io.github.ygrip.testara.agent.index.TestaraProjectProfile;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.logging.Logger;
import java.util.stream.Collectors;

/**
 * Skill: generate a Testara-compatible Cucumber .feature file from user intent.
 * Unknown steps are explicitly marked as MISSING to prevent hallucination.
 *
 * When context option "write=true", the feature file is saved to disk at the resolved placement path.
 */
public class TestPlanSkill implements AgentSkill<TestPlanSkill.Input, String> {

  private static final Logger LOG = Logger.getLogger(TestPlanSkill.class.getName());

  public record Input(String intent, String slice, String domain, List<String> tags) {}

  @Override
  public String name() { return "test-plan"; }

  @Override
  public String execute(Input input, AgentContext context) {
    TestaraProjectProfile profile = context.profile();
    String slice  = input.slice() != null ? input.slice() : "api";
    String domain = input.domain() != null ? input.domain() : inferDomain(input.intent());
    List<String> tags = buildTags(input.tags(), slice, domain);
    boolean write = "true".equals(context.options().get("write"));

    String featureContent = generateFeature(input.intent(), domain, tags, slice, profile);
    String placement      = resolvePlacement(slice, domain);
    String fileName       = toFileName(input.intent());
    boolean concise = "concise".equals(context.options().get("format"));

    String writtenPath = null;
    if (write) {
      writtenPath = writeFeatureFile(context.projectRoot(), placement, fileName, featureContent);
    }

    if (concise) {
      StringBuilder sb = new StringBuilder();
      if (write) {
        sb.append(writtenPath != null ? "written: " + writtenPath : "write failed");
        sb.append("\n\n");
      }
      sb.append(featureContent);
      List<String> missing = extractMissingSteps(featureContent);
      if (!missing.isEmpty()) {
        sb.append("\nmissing steps (").append(missing.size()).append("): ");
        sb.append(String.join(", ", missing));
      }
      return sb.toString();
    }

    StringBuilder sb = new StringBuilder();
    sb.append("## Test Plan: ").append(input.intent()).append("\n\n");
    sb.append("**Placement:** `").append(placement).append(fileName).append("`\n\n");
    if (write) {
      sb.append(writtenPath != null
          ? "> Written to `" + writtenPath + "`\n\n"
          : "> Warning: could not write feature file.\n\n");
    }
    sb.append("```gherkin\n").append(featureContent).append("\n```\n\n");
    List<String> missingSteps = extractMissingSteps(featureContent);
    if (!missingSteps.isEmpty()) {
      sb.append("**Missing steps:** ");
      missingSteps.forEach(s -> sb.append("`").append(s).append("` "));
      sb.append("\nImplement in `StepDefinitions.java` before running.\n");
    }
    if (write && writtenPath != null) {
      sb.append("\nNext: `testara-agent test-run '").append(input.intent()).append("' --execute`\n");
    }
    return sb.toString();
  }

  private String writeFeatureFile(Path projectRoot, String placement, String fileName, String content) {
    try {
      Path dir = projectRoot.resolve(placement);
      Files.createDirectories(dir);
      Path file = dir.resolve(fileName);
      Files.writeString(file, content, StandardCharsets.UTF_8);
      return projectRoot.relativize(file).toString();
    } catch (IOException e) {
      LOG.warning("Cannot write feature file: " + e.getMessage());
      return null;
    }
  }

  private String generateFeature(String intent, String domain, List<String> tags,
      String slice, TestaraProjectProfile profile) {
    String featureName = toFeatureName(intent);
    String tagLine     = tags.stream().collect(Collectors.joining(" "));
    boolean isApi      = "api".equalsIgnoreCase(slice);

    Set<String> knownExpressions = profile.stepDefinitions().stream()
        .map(StepDefinitionIndex::expression).collect(Collectors.toSet());

    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by Testara Agent.\n");
    sb.append("# Source request: ").append(intent).append("\n");
    sb.append("# Review before committing.\n\n");
    sb.append(tagLine).append("\n");
    sb.append("Feature: ").append(featureName).append("\n\n");

    if (isApi) {
      String service = domain + "-service";
      sb.append("  Background:\n");
      String bgStep = "the API service \"" + service + "\" is available";
      String bgKeyword = matchStep(bgStep, knownExpressions) ? "Given" : "Given # MISSING";
      sb.append("    ").append(bgKeyword).append(" ").append(bgStep).append("\n\n");
    }

    sb.append("  @P1 @positive\n");
    sb.append("  Scenario: ").append(featureName).append(" — happy path\n");
    appendSliceSteps(sb, intent, domain, slice, knownExpressions, false);
    sb.append("\n");

    sb.append("  @P2 @negative\n");
    sb.append("  Scenario: ").append(featureName).append(" — failure case\n");
    appendSliceSteps(sb, intent, domain, slice, knownExpressions, true);

    return sb.toString();
  }

  private void appendSliceSteps(StringBuilder sb, String intent, String domain,
      String slice, Set<String> known, boolean negative) {
    List<String[]> steps = generateSteps(intent, domain, slice, negative);
    for (String[] step : steps) {
      String keyword = step[0];
      String text    = step[1];
      String suffix  = matchStep(text, known) ? "" : " # MISSING";
      sb.append("    ").append(keyword).append(" ").append(text).append(suffix).append("\n");
    }
  }

  private List<String[]> generateSteps(String intent, String domain, String slice, boolean negative) {
    String verb = extractVerb(intent);
    String noun = extractNoun(intent, domain);

    return switch (slice.toLowerCase(Locale.ROOT)) {
      case "api" -> negative
          ? List.of(
              new String[]{"Given", "a request to " + verb + " " + noun + " with invalid data"},
              new String[]{"When",  "the request is sent"},
              new String[]{"Then",  "the response status should be 400"},
              new String[]{"And",   "the response should contain an error message"})
          : List.of(
              new String[]{"Given", "a valid request to " + verb + " " + noun},
              new String[]{"When",  "the request is sent"},
              new String[]{"Then",  "the response status should be 200"},
              new String[]{"And",   "the response should contain the expected " + noun + " data"});
      case "ui" -> negative
          ? List.of(
              new String[]{"Given", "the user is on the " + domain + " page"},
              new String[]{"When",  "the user attempts to " + verb + " " + noun + " with invalid input"},
              new String[]{"Then",  "an error message should be displayed"})
          : List.of(
              new String[]{"Given", "the user is on the " + domain + " page"},
              new String[]{"When",  "the user " + verb + "s " + noun},
              new String[]{"Then",  "the " + noun + " should be successfully " + verb + "d"},
              new String[]{"And",   "a success notification should appear"});
      default -> List.of(
          new String[]{"Given", "the system is in a valid state for " + noun},
          new String[]{"When",  "the " + verb + " operation is performed on " + noun},
          new String[]{"Then",  "the expected result should be " + (negative ? "an error" : "success")});
    };
  }

  private boolean matchStep(String text, Set<String> known) {
    return known.stream().anyMatch(expr -> {
      String pattern = expr.replaceAll("\\{[^}]+\\}", ".*").replaceAll("\\(.*?\\)", ".*");
      return text.toLowerCase(Locale.ROOT).matches(".*" + pattern.toLowerCase(Locale.ROOT) + ".*");
    });
  }

  private List<String> extractMissingSteps(String featureContent) {
    return Arrays.stream(featureContent.split("\n"))
        .filter(l -> l.contains("# MISSING"))
        .map(l -> l.replaceAll(".*(?:Given|When|Then|And|But)\\s+", "")
            .replace("# MISSING", "").strip())
        .collect(Collectors.toList());
  }

  private String resolvePlacement(String slice, String domain) {
    return switch (slice.toLowerCase(Locale.ROOT)) {
      case "api"       -> "src/test/resources/features/api/" + domain + "/";
      case "ui"        -> "src/test/resources/features/ui/" + domain + "/";
      case "database"  -> "src/test/resources/features/database/" + domain + "/";
      case "streaming" -> "src/test/resources/features/streaming/" + domain + "/";
      default          -> "src/test/resources/features/" + domain + "/";
    };
  }

  private String toFileName(String intent) {
    return intent.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+", "-")
        .replaceAll("^-|-$", "").substring(0, Math.min(50, intent.length())) + ".feature";
  }

  private String inferDomain(String intent) {
    String lower = intent.toLowerCase(Locale.ROOT);
    for (String word : new String[]{"payment","order","user","product","cart","checkout",
        "login","auth","refund","search","catalog","notification","inventory"}) {
      if (lower.contains(word)) return word;
    }
    return intent.replaceAll("[^a-zA-Z0-9]+", "-").toLowerCase(Locale.ROOT)
        .replaceAll("^-|-$", "").substring(0, Math.min(20, intent.length()));
  }

  private String extractVerb(String intent) {
    String lower = intent.toLowerCase(Locale.ROOT);
    for (String verb : new String[]{"create","update","delete","get","fetch","submit",
        "approve","reject","cancel","confirm","process","validate","search"}) {
      if (lower.contains(verb)) return verb;
    }
    return "process";
  }

  private String extractNoun(String intent, String domain) {
    String lower = intent.toLowerCase(Locale.ROOT).replace(domain, "").strip();
    String[] words = lower.split("\\s+");
    for (int i = words.length - 1; i >= 0; i--) {
      String w = words[i].replaceAll("[^a-z]", "");
      if (w.length() > 3) return w;
    }
    return domain;
  }

  private List<String> buildTags(List<String> userTags, String slice, String domain) {
    List<String> tags = new ArrayList<>();
    tags.add("@" + slice.toLowerCase(Locale.ROOT));
    tags.add("@" + domain.toLowerCase(Locale.ROOT));
    tags.add("@regression");
    if (userTags != null) userTags.forEach(t -> tags.add(t.startsWith("@") ? t : "@" + t));
    return tags;
  }

  private String toFeatureName(String intent) {
    return intent.substring(0, 1).toUpperCase(Locale.ROOT) + intent.substring(1).toLowerCase(Locale.ROOT);
  }
}
