package io.github.ygrip.testara.agent.skill;

import java.util.*;

/**
 * Skill: generate a Testara validation — either a JSON file or a ValidatorLogic Java class.
 */
public class TestValidationSkill implements AgentSkill<String, String> {

  private static final List<String> BUILT_IN = List.of(
      "EQUAL", "NOT_EQUAL", "EMPTY", "NOT_EMPTY", "CONTAINS", "CONTAINS_TEXT",
      "STARTS_WITH", "ENDS_WITH", "MATCH_PATTERN", "HAS_SIZE", "GREATER_THAN",
      "LESSER_THAN", "IN_RANGE_OF", "SORTED", "CONTAINS_KEY", "MATCH_SCHEMA");

  private static final Map<String, String> KEYWORD_MAP = Map.ofEntries(
      Map.entry("equal",         "EQUAL"),
      Map.entry("same",          "EQUAL"),
      Map.entry("not equal",     "NOT_EQUAL"),
      Map.entry("empty",         "EMPTY"),
      Map.entry("not empty",     "NOT_EMPTY"),
      Map.entry("contains",      "CONTAINS"),
      Map.entry("include",       "CONTAINS"),
      Map.entry("starts with",   "STARTS_WITH"),
      Map.entry("ends with",     "ENDS_WITH"),
      Map.entry("match",         "MATCH_PATTERN"),
      Map.entry("pattern",       "MATCH_PATTERN"),
      Map.entry("size",          "HAS_SIZE"),
      Map.entry("count",         "HAS_SIZE"),
      Map.entry("greater",       "GREATER_THAN"),
      Map.entry("more than",     "GREATER_THAN"),
      Map.entry("less than",     "LESSER_THAN"),
      Map.entry("range",         "IN_RANGE_OF"),
      Map.entry("between",       "IN_RANGE_OF"),
      Map.entry("sorted",        "SORTED"),
      Map.entry("ordered",       "SORTED"),
      Map.entry("has key",       "CONTAINS_KEY"),
      Map.entry("schema",        "MATCH_SCHEMA")
  );

  @Override
  public String name() { return "test-validation"; }

  @Override
  public String execute(String description, AgentContext context) {
    String mode = context.options().getOrDefault("mode", "auto");
    String pkg  = context.options().getOrDefault("package", "com.company.automation.validators");

    String resolved = resolveBuiltIn(description.toLowerCase(Locale.ROOT));
    boolean useJson = "json".equals(mode) || ("auto".equals(mode) && resolved != null);

    StringBuilder sb = new StringBuilder();
    sb.append("## Generated Validation\n\n**Description:** ").append(description).append("\n\n");

    if (useJson && resolved != null) {
      sb.append("**Mode:** JSON (uses built-in validator `").append(resolved).append("`)\n\n");
      sb.append("### validation.json\n\n```json\n");
      sb.append(generateValidationJson(resolved, description));
      sb.append("\n```\n\n");
      sb.append("**Placement:** `src/test/resources/validations/<domain>/<name>.json`\n");
    } else {
      String className = toClassName(description) + "Validator";
      sb.append("**Mode:** Java (custom ValidatorLogic)\n\n");
      sb.append("### ").append(className).append(".java\n\n```java\n");
      sb.append(generateValidatorClass(className, description, pkg));
      sb.append("```\n\n");
      sb.append("**Placement:** `src/test/java/").append(pkg.replace('.', '/')).append("/")
          .append(className).append(".java`\n\n");
      sb.append("**Scan config:**\n```properties\n");
      sb.append("validator.scan-locations=io.github.ygrip.testara,").append(pkg).append("\n```\n");
    }
    return sb.toString();
  }

  private String resolveBuiltIn(String desc) {
    for (Map.Entry<String, String> entry : KEYWORD_MAP.entrySet()) {
      if (desc.contains(entry.getKey())) return entry.getValue();
    }
    return null;
  }

  private String generateValidationJson(String validator, String description) {
    return """
        {
          "validation": "%s",
          "description": "%s",
          "expected": null
        }""".formatted(validator, description.replace("\"", "\\\""));
  }

  private String generateValidatorClass(String className, String description, String pkg) {
    return """
        package %s;

        import io.github.ygrip.testara.validation.model.ValidatorLogic;
        import io.github.ygrip.testara.validation.model.ValidationTag;

        /**
         * %s
         * Generated by Testara Agent — review before committing.
         */
        @ValidationTag(command = "%s")
        public class %s extends ValidatorLogic<Object, Object> {

          @Override
          protected String setDefaultMessage() {
            return "%s validation failed";
          }

          @Override
          public boolean validate() throws Exception {
            // TODO: implement validation logic
            // getActual() — the actual value from the test
            // getExpected() — the expected value from the step
            throw new UnsupportedOperationException("Not yet implemented");
          }
        }
        """.formatted(pkg, description, toValidationName(description), className, className);
  }

  private String toValidationName(String description) {
    return description.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+", "-")
        .replaceAll("^-|-$", "").substring(0, Math.min(40, description.length()));
  }

  private String toClassName(String description) {
    String[] parts = description.replaceAll("[^a-zA-Z0-9]+", " ").trim().split("\\s+");
    StringBuilder sb = new StringBuilder();
    for (String p : parts) {
      if (!p.isBlank()) sb.append(Character.toUpperCase(p.charAt(0))).append(p.substring(1).toLowerCase(Locale.ROOT));
    }
    return sb.toString();
  }
}
